name: Build Check

on:
  pull_request:
    branches: [main, master] # or whatever your default branch is

jobs:
  build:
    runs-on: ubuntu-latest # or whatever OS you need

    steps:
      - uses: actions/checkout@v2

      # If you're using Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # or whatever version you need

      # Install dependencies
      - name: Install dependencies
        run: npm install # or yarn install, etc.

      # Run build
      - name: Build
        run: npm run build # or your build command
