name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  gen-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1
      - name: Install dependencies
        run: |
          bun install
      - name: Run print-pdf from scripts dir
        run: |
          node scripts/print-pdf.cjs ${{needs.deploy.outputs.page_url}}
      - name: Commit updated CV PDFs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "chore(docs): update CV PDFs [skip ci]"
          git pull --rebase
          git push

  psi-insights:
    env:
      RESULTS_DIR: docs/img
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Run psi-svg
        run: | # Have to be sure a folder is present if not, make it
          mkdir -p ${RESULTS_DIR}
          bunx psi-svg ${{needs.deploy.outputs.page_url}} $RESULTS_DIR/desktop.svg -s=desktop --categories=performance,accessibility,best-practices,seo
          bunx psi-svg ${{needs.deploy.outputs.page_url}} $RESULTS_DIR/mobile.svg -s=mobile --categories=performance,accessibility,best-practices,seo
      - name: Commit updated PageSpeed Insights SVGs
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "chore(docs): update PageSpeed Insights SVGs [skip ci]"
          git pull --rebase
          git push
